server:
  port: 8888

eureka:
  instance:
    hostname: LCloud
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/